# Generated by Django 4.0.2 on 2022-02-25 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_department_direction_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Staff',
        ),
    ]
